server:
  port: 8080

spring:
  profiles:
    active:
    - local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  file: logs/application.log
  level:
    com.example: DEBUG
    
---

